language: ruby
rvm:
- 2.2.2

branches:
  only:
  - master

gemfile:
- Gemfile

notifications:
  email:
  - antonioreuter@gmail.com
  - aandrade@avenuecode.com

addons:
  code_climate:
    repo_token: d0783aeafec1eae9a4f911092cfc0dba0ad3cc5a92b20f1b679a7476a28f706b

deploy:
  provider: heroku
  api_key:
    secure: XyF9ABdyqgwJBgCnXMLjER4ksj9kVvsRvNYP98GFrlI/hqTD+8twsxHyNwpygaJBCGA9epUrrIx1O8EI012jFikBDqcxv5y6XjZwe9QjvjFGvhxUOIQVM7nOqEqV4neBoo5WdgVY1QDH2pgnpEWmaa23vGXpj0pfgS44Xt/Ezv5JQb86wmeThfR7kzXscokBzrNIw4aUSzT+kpmUY5/Nijy9+Bo6OoqNWCyFEZbPDRwNAdRFnEUsaN/xSVc6cDIGAku9zzebj4JKTsCw/X1VT67NR2MLdYBnceDbILGcd1pyLTLzVK1OAXn9Yox0Bncdcnpyd8D75br2Ba46rjL+0towkuAjasNRYtImRzDZ17RIQd3Ih2mE1AygoMsP9Y1ljlIS/zcnsnp59ZlWnsFG6UY80QwepnUE61GUXaED501OvgZlOhAaEJJDVvY0qRXNH2ZlIMi5m4Hx/0Hwv/e106Ju9oTj567HES2FyxmMO1ofO+iLTlAHKehruMiQ75az4SZI99Cgy+kCLVnm9u3usZP0vJmws1N2huV1+9FhwWHCzr4lfMgwh3lIVXwEeoe3PzEPLnyInZyPmS9D4YRgRGWLJmPevK2PFcpyIMMJGpEFsA6Hv2k/fdi9dY1yPZl6bZKSrEFX1NGAjrsgcGUg1L0KPKtB5ibv9yqwwXMmo64=
  app: omeupet
  on:
    repo: antonioreuter/meupet
  run:
    - "rake db:migrate"
    - restart
